Repository GroupProject-JOM/Frontend-web-, pull requests merged in 2023-09, with the labels that each got.

#33 fixed date in supply
  common/style.css
  supplier/supply2.html
  supplier/supply3.html
Labels: documentation

#35 remove sppuly
  supplier/sppuly1.html
Labels: bug

#36 fixed stock manager table overlap
  common/style.css
  stock-manager/index.html
Labels: documentation

#38 set nv close
  admin/index.html
  collector/index.html
  common/style.css
  distributor/index.html
  production-manager/index.html
  sales-manager/index.html
  stock-manager/index.html
  stock-manager/style.css
Labels: enhancement

#41 added supply6
  supplier/supply.css
  supplier/supply6.html
Labels: documentation

#42 supply8
  supplier/supply8.html
  supplier/supply9.html
Labels: documentation

#43 Dev
  admin/index.html
  collector/index.html
  common/style.css
  distributor/index.html
  production-manager/index.html
  sales-manager/index.html
  stock-manager/index.html
  stock-manager/style.css
  supplier/supply.css
  supplier/supply2.html
  supplier/supply3.html
  supplier/supply6.html
  supplier/supply7.html
  supplier/supply8.html
  supplier/supply9.html
Labels: enhancement

#44 minor style changes
  supplier/supply.css
  supplier/supply6.html
  supplier/supply8.html
  supplier/supply9.html
Labels: enhancement

#45 added darkmode colors in supply
  common/style.css
  supplier/supply.css
  supplier/supply1.html
Labels: enhancement

#46 fixed input background
  common/style.css
  supplier/supply.css
Labels: enhancement

#47 signup page5
  signin.css
  signup5.html
  signup5.js
Labels: documentation

#49 set nav selecter
  admin/index.html
  collector/index.html
  common/func.js
  distributor/index.html
  production-manager/index.html
  sales-manager/index.html
  signin.css
  signin.html
  stock-manager/index.html
  stock-manager/style.css
  supplier/index.html
  supplier/nav/nav.html
  supplier/nav/script.js
  supplier/supply1.html
Labels: enhancement

#50 fixed signup 5
  signup5.html
  signup5.js
Labels: documentation

#52 scroll bar width
  common/notify.css
  common/style.css
Labels: documentation

#53 separate signup and supply pages
  common/func.js
  signup/sidebar/load-sidebar.js
  signup/sidebar/script.js
  signup/sidebar/sidebar.html
  signup/signup1.html
  signup/signup1.js
  signup/signup2.html
  signup/signup2.js
  signup/signup3.html
  signup/signup3.js
  signup/signup4.html
  signup/signup4.js
  signup/signup5.html
  signup/signup5.js
  signup4.html
  supplier/index.html
  supplier/nav/nav.html
  supplier/supply/load-nav.js
  supplier/supply/load-notifications.js
  supplier/supply/supply.css
  supplier/supply/supply1.html
  supplier/supply/supply2.html
  supplier/supply/supply3.html
  supplier/supply/supply4.html
  supplier/supply/supply5.html
  supplier/supply/supply6.html
  supplier/supply/supply7.html
  supplier/supply/supply8.html
  supplier/supply/supply9.html
Labels: bug

#56 Update README.md
  README.md
Labels: enhancement

#59 set onload nav active status
  common/func.js
  supplier/nav/nav.html
  supplier/nav/script.js
  supplier/supply/supply1.html
  supplier/supply/supply2.html
  supplier/supply/supply3.html
  supplier/supply/supply4.html
  supplier/supply/supply5.html
  supplier/supply/supply6.html
  supplier/supply/supply7.html
  supplier/supply/supply8.html
  supplier/supply/supply9.html
Labels: bug

#60 dark mode active issue fixed
  common/nav.css
Labels: bug

#61 fixed supply naming
  supplier/address/address1.html
  supplier/address/address2.html
  supplier/address/load-nav.js
  supplier/address/load-notifications.js
  supplier/payment/load-nav.js
  supplier/payment/load-notifications.js
  supplier/payment/payment1.html
  supplier/payment/payment2.html
  supplier/supply.css
  supplier/supply/supply1.html
  supplier/supply/supply2.html
  supplier/supply/supply3.html
  supplier/supply/supply4.html
  supplier/supply/supply5.html
Labels: bug

#62 minor style changes
  common/style.css
  signin.css
  signin.js
  signup/signup1.html
  signup/signup2.html
  signup/signup2.js
  signup/signup3.html
  signup/signup3.js
  signup/signup4.html
  signup/signup4.js
  signup/signup5.html
  signup/signup5.js
  supplier/address/add.html
  supplier/address/edit.html
  supplier/address/view-all.html
  supplier/address/view.html
  supplier/payment/add.html
  supplier/payment/edit.html
  supplier/payment/view-all.html
  supplier/payment/view.html
  supplier/supply.css
  supplier/supply/new.html
  supplier/supply/pickup-bank.html
  supplier/supply/pickup-cash.html
  supplier/supply/yard-bank.html
  supplier/supply/yard-cash.html
Labels: enhancement

#64 Added dashbaord to nav
  admin/nav/nav.html
  collector/nav/nav.html
  distributor/nav/nav.html
  production-manager/nav/nav.html
  sales-manager/nav/nav.html
  stock-manager/nav/nav.html
  supplier/nav/nav.html
Labels: duplicate

#66 supplier nav bar active status fixed
  supplier/nav/nav.html
  supplier/nav/script.js
Labels: bug

#65 Signup side nav load issue fixed
  signin.css
  signup/sidebar/script.js
  signup/sidebar/sidebar.html
Labels: bug

#68 coconut collection pages
  collector/collection/collection.css
  collector/collection/complete.html
  collector/collection/view.html
  supplier/supply.css
  supplier/supply/new.html
Labels: documentation

#69 Added map to collection
  collector/collection/view.html
  stock-manager/style.css
Labels: bug

#70 Added deleted styles
  stock-manager/style.css
Labels: bug

#71 styles of collection map
  collector/collection/collection.css
  collector/collection/complete.html
  collector/collection/view.html
Labels: enhancement

#72 added pages
  collector/collection/collection.css
  collector/collection/completed.html
  collector/collection/enter-amount.html
  collector/collection/pending-verify.html
  collector/collection/verify-amount.html
  collector/collection/view.html
Labels: enhancement

#73 Set row to view page and nav
  collector/collection/load-nav.js
  collector/collection/load-notifications.js
  collector/index.html
  collector/script.js
Labels: bug

#74 added pages
  stock-manager/track-collectors/collection.html
  stock-manager/track-collectors/view-all.html
  stock-manager/user-flow.css
Labels: documentation

#75 Changed nav close left padding
  common/nav.css
Labels: bug

#76 stock manager 2pages
  stock-manager/track-collectors/collection.html
  stock-manager/track-collectors/view-all.html
  stock-manager/user-flow.css
  supplier/address/view-all.html
Labels: documentation

#77 added pages for stockmg
  stock-manager/accepted-request.html
  stock-manager/assign-collector.html
  stock-manager/supply-request.html
  stock-manager/view-request.html
Labels: documentation

#80 Feat/back
  admin/notifications/notifications.html
  collector/notifications/notifications.html
  common/style.css
  distributor/notifications/notifications.html
  production-manager/notifications/notifications.html
  sales-manager/notifications/notifications.html
  signup/signup1.html
  signup/signup1.js
  stock-manager/notifications/notifications.html
  supplier/notifications/notifications.html
Labels: help wanted

#81 Path relative issue fixed
  signup/signup1.html
  signup/signup1.js
  supplier/nav/nav.html
  supplier/nav/script.js
Labels: bug

#82 Basic form submit validation added
  common/style.css
  signin.css
  signup/signup1.html
  signup/signup1.js
Labels: help wanted

#83 Backend error handled
  common/style.css
  signup/signup1.html
  signup/signup1.js
Labels: documentation

#84 Signup nav bar status dynamic
  signin.css
  signup/sidebar/script.js
  signup/sidebar/sidebar.html
  supplier/nav/script.js
Labels: documentation

#85 Basic signup bugs fixed
  signup/signup1.js
Labels: documentation

#86 Feat/signup
  signin.js
  signup/signup1.js
  signup/signup2.html
  signup/signup2.js
  signup/signup3.html
  signup/signup4.html
  signup/signup5.html
  supplier/index.html
  supplier/script.js
Labels: documentation

#87 signup role
  signin.js
  signup/signup1.js
Labels: documentation

#88 added send otp option
  collector/collection/completed.html
  collector/collection/pending-verify.html
  collector/collection/verify-amount.html
  signin.css
  signup/signup1.html
  signup/signup2.html
  signup/signup2.js
  stock-manager/accepted-request.html
  stock-manager/assign-collector.html
  stock-manager/supply-request.html
  stock-manager/view-request.html
Labels: enhancement
