Repository GroupProject-JOM/Frontend-web-, pull requests merged in 2024-02, with the labels that each got.

#416 Refactor id format, Employee full name, view employee buttons
  admin/collection/view-all.js
  admin/employee/view-all.js
  admin/user-flow.css
  distributor/outlets/add.js
  distributor/outlets/edit.js
  distributor/outlets/view-all.html
  distributor/outlets/view-all.js
  distributor/products/view-all.js
  distributor/script.js
Labels: documentation

#418 edit ID format
  distributor/outlets/view-all.js
  distributor/products/view-all.js
  distributor/script.js
  production-manager/production-requests/view.js
  production-manager/production/add.js
  production-manager/production/script.js
  production-manager/products/view-all.js
  production-manager/script.js
  production-manager/stock/request.js
  production-manager/stock/view.js
  sales-manager/distributors/view.js
  sales-manager/outlet/script.js
  sales-manager/outlet/view.js
  sales-manager/productions/view-all.js
  sales-manager/productions/view.js
  sales-manager/products/view-all.js
  stock-manager/production-requests/view-all.js
  stock-manager/production-requests/view-request.js
  stock-manager/script.js
  stock-manager/stock/edit.js
  stock-manager/stock/view-all.js
  stock-manager/stock/view-block.js
Labels: documentation

#420 New production batch request not added bug and supplier view profile bug
  production-manager/production/add.js
  stock-manager/production-requests/view-request.js
  supplier/profile/view.js
Labels: fixed

#421 Production manager ID not set properly bug fixed
  production-manager/production/view.js
  production-manager/script.js
Labels: fixed

#422 Sales manager view distributor product id fixed
  sales-manager/distributors/view.js
Labels: fixed

#423 Reject table added and its content
  supplier/index.html
  supplier/script.js
  supplier/supply-view.js
Labels: documentation, fixed

#424 Hide complete collection button from relevant supplies
  stock-manager/supply-requests/view-request.js
Labels: fixed

#426 Pagination for admin stock manager
  admin/employee/view-all.html
  admin/employee/view-all.js
  stock-manager/all-collections/index.html
  stock-manager/all-collections/script.js
  stock-manager/index.html
  stock-manager/script.js
Labels: documentation

#427 pagination button styles
  common/style.css
Labels: documentation

#428 Evening time to 4PM and function js code formatting and pending js pa…
  collector/collection/pending.js
  common/func.js
Labels: documentation

#430 Fixed notification time bug
  common/func.js
Labels: documentation

#433 missed collections table
  collector/collection.css
  collector/index.html
  collector/script.js
  common/style.css
Labels: enhancement

#434 fixed styles in add to yard page
  sales-manager/productions/view.html
  sales-manager/user-flow.css
  stock-manager/supply-requests/view-request.html
  stock-manager/user-flow.css
Labels: fixed

#435 All setup for refresh token
  admin/auth.js
  collector/auth.js
  common/func.js
  distributor/auth.js
  forgot-password/load-sidebar.js
  production-manager/auth.js
  sales-manager/auth.js
  signin.js
  signup/sidebar/load-sidebar.js
  stock-manager/auth.js
  supplier/auth.js
Labels: documentation

#437 New password rules added
  signup/index.html
  signup/script.js
Labels: documentation

#436 minor language changes
  signup/index.html
  signup/script.js
Labels: documentation

#441 Update func.js
  common/func.js
Labels: documentation

#442 Set spelling mistakes
  supplier/script.js
Labels: documentation

#443 Dev
  supplier/script.js
Labels: documentation

#444 language fix for stockmg, tabs for all collections
  common/style.css
  stock-manager/all-collections/index.html
  stock-manager/all-collections/script.js
  stock-manager/chat/chat.html
  stock-manager/chat/chat.js
  stock-manager/collectors/view-all.js
  stock-manager/collectors/view.js
  stock-manager/production-requests/view-request.js
  stock-manager/profile/edit.js
  stock-manager/profile/view.js
  stock-manager/script.js
  stock-manager/stock/edit.js
  stock-manager/stock/view-all.js
  stock-manager/stock/view-block.js
  stock-manager/supply-requests/assign-collector.js
  stock-manager/supply-requests/view-request.js
  stock-manager/user-flow.css
Labels: enhancement, fixed

#445 Scroll indicator
  stock-manager/all-collections/index.html
  stock-manager/all-collections/script.js
  stock-manager/user-flow.css
Labels: enhancement

#446 Small process buds and id bugs fixed
  admin/outlet/script.js
  admin/outlet/view.js
  admin/products/view-all.js
  admin/stock/view-all.js
  admin/stock/view-block.js
  common/chat.css
  production-manager/production/add.html
  production-manager/production/add.js
  sales-manager/payouts/view-all.js
  sales-manager/productions/view.html
  sales-manager/productions/view.js
  sales-manager/products/view-all.js
  stock-manager/all-collections/index.html
  stock-manager/all-collections/script.js
Labels: documentation, fixed
