Repository GroupProject-JOM/Frontend-web-, pull requests merged in 2024-03, with the labels that each got.

#447 Missed collections table and data functions
  collector/index.html
  collector/script.js
Labels: documentation, enhancement

#449 Manifest added
  common/img/Jayasinghe-Oil-Mils-Logo.jpg
  common/img/android-chrome-192x192.png
  common/img/android-chrome-512x512.png
  common/img/apple-touch-icon.png
  common/img/favicon-16x16.png
  common/img/favicon-32x32.png
  common/img/favicon.ico
  common/img/icon-192x192.png
  common/img/icon-256x256.png
  common/img/icon-384x384.png
  common/img/icon-512x512.png
  common/loader.js
  common/meta.html
  index.html
  signup/signup4.html
  site.webmanifest
  supplier/reports/report.js
Labels: documentation

#451 Update func.js
  common/func.js
Labels: documentation

#453 Update deploy.yml
  .github/workflows/deploy.yml
Labels: documentation

#454 Fix/style
  admin/collection/view.js
  admin/employee/view-all.js
  admin/index.html
  admin/nav/nav.html
  admin/nav/script.js
  admin/script.js
  collector/collection-history/script.js
  collector/index.html
  collector/nav/nav.html
  collector/nav/script.js
  collector/script.js
  distributor/index.html
  distributor/nav/nav.html
  distributor/script.js
  production-manager/index.html
  production-manager/nav/nav.html
  production-manager/user-flow.css
  sales-manager/index.html
  sales-manager/nav/nav.html
  sales-manager/productions/view.js
  stock-manager/collectors/view.html
  stock-manager/collectors/view.js
  stock-manager/index.html
  stock-manager/nav/nav.html
  supplier/index.html
  supplier/nav/nav.html
Labels: fixed

#455 Pending products hide
  sales-manager/products/view-all.html
  sales-manager/products/view-all.js
Labels: enhancement, fixed

#456 Dry run bugs fixed
  collector/collection-history/script.js
  collector/upcoming-collections/script.js
  sales-manager/productions/view-all.js
  sales-manager/productions/view.js
  stock-manager/collectors/view.js
  stock-manager/stock/edit.html
  stock-manager/stock/edit.js
  stock-manager/supply-requests/view-request.js
  supplier/supply/script.js
Labels: enhancement, fixed

#457 Meta test
  admin/collection/view.js
  admin/employee/view-all.js
  admin/index.html
  admin/nav/nav.html
  admin/nav/script.js
  admin/script.js
  collector/collection-history/script.js
  collector/index.html
  collector/nav/nav.html
  collector/nav/script.js
  collector/script.js
  collector/upcoming-collections/script.js
  common/loader.js
  distributor/index.html
  distributor/nav/nav.html
  distributor/script.js
  index.html
  production-manager/index.html
  production-manager/nav/nav.html
  production-manager/user-flow.css
  sales-manager/index.html
  sales-manager/nav/nav.html
  sales-manager/productions/view-all.js
  sales-manager/productions/view.js
  sales-manager/products/view-all.html
  sales-manager/products/view-all.js
  stock-manager/collectors/view.html
  stock-manager/collectors/view.js
  stock-manager/index.html
  stock-manager/nav/nav.html
  stock-manager/stock/edit.html
  stock-manager/stock/edit.js
  stock-manager/supply-requests/view-request.js
  supplier/index.html
  supplier/nav/nav.html
  supplier/supply/script.js
Labels: documentation, fixed

#458 Landing pages
  common/img/Coconut Land 1 (1).png
  common/img/Coconut Land 1.png
  common/img/step-1.png
  common/img/step-2.png
  common/img/step-3.png
  common/img/step-4.png
  common/img/step-5.png
  landing/process.css
  landing/process.html
  landing/product.css
  landing/products.html
Labels: enhancement

#459 added bill for outlets
  distributor/outlets/update-sales.html
  distributor/outlets/update-sales.js
  distributor/user-flow.css
Labels: enhancement
