Repository GroupProject-JOM/Frontend-web-, pull requests merged in 2024-04, with the labels that each got.

#464 Pick and edit picked locations done
  common/map.css
  signup/signup3.html
  signup/signup3.js
  supplier/address/add.html
  supplier/address/add.js
  supplier/address/edit.html
  supplier/address/edit.js
Labels: enhancement

#465 Stock manager view all collections on map
  stock-manager/collectors/view.html
  stock-manager/collectors/view.js
Labels: enhancement

#466 Get direction
  collector/collection.css
  collector/index.html
  collector/script.js
  common/map.css
  common/style.css
  supplier/address/add.js
Labels: enhancement, fixed

#468 View all on map
  collector/index.html
  collector/script.js
Labels: documentation

#473 fire works bug fixed
  collector/script.js
Labels: fixed

#475 index page fixed, scroll button
  landing/index.html
  landing/landing.css
  landing/process.html
  landing/product.css
  landing/products.html
Labels: enhancement

#476 Landing pages
  common/img/Coconut Land 1 (1).png
  common/img/Coconut Land 1.png
  common/img/g-e3.jpg
  common/img/g-e4.jpeg
  common/img/g-e5.jpg
  common/img/gallary-e2.jpeg
  common/img/gallary-p1.jpg
  common/img/gallary-p2.jpg
  common/img/gallary-p3.jpg
  common/img/gallary-p4.jpg
  common/img/gallary-p5.jpg
  common/img/gallary-s2.jpg
  common/img/gallary-s3.jpg
  common/img/gallary-s4.jpg
  common/img/gallary-s5.jpg
  common/img/gallary-w2.jpg
  common/img/gallary-w3.jpg
  common/img/gallary-w4.jpg
  common/img/gallary-w5.jpg
  common/img/landing-layer1.png
  common/img/landing-shape2-4.jpg
  common/img/landing1.png
  common/img/product1.png
  common/img/product2.png
  common/img/product3.png
  common/img/product4.png
  common/img/product5.png
  common/img/step-1.png
  common/img/step-2.png
  common/img/step-3.png
  common/img/step-4.png
  common/img/step-5.png
  index.html
  landing.css
  process.css
  process.html
  product.css
  products.html
Labels: documentation, fixed

#479 more products added, minor style changes
  index.html
  landing.css
  process.css
  process.html
  products.html
Labels: enhancement

#480 added activity logs page
  sales-manager/activity/index.html
  sales-manager/nav/nav.html
  sales-manager/nav/script.js
  sales-manager/user-flow.css
Labels: enhancement

#481 Sales Manager dashboard charts and activity logs of product distributions
  distributor/outlets/update-sales.js
  sales-manager/activity/index.html
  sales-manager/activity/script.js
  sales-manager/index.html
  sales-manager/script.js
Labels: documentation

#482 Landing pages minor bugs fixed
  index.html
  landing.css
  process.css
  process.html
  product.css
  products.html
  sales-manager/script.js
Labels: fixed

#483 added price, fixed styles
  sales-manager/activity/script.js
  sales-manager/user-flow.css
Labels: enhancement

#484 Product page sweet alert
  products.html
Labels: documentation

#485 Activity logs filtered by date
  sales-manager/activity/index.html
  sales-manager/activity/script.js
Labels: documentation

#492 Optional verification otp submission error fixed
  collector/collection/pending.html
  collector/collection/pending.js
Labels: fixed

#495 mobile app link to footer
  common/img/collector_qr.png
  common/img/web_qr.png
  index.html
  landing.css
Labels: enhancement

#496 landing pages styles, supply edit, reports
  collector/collection/pending.js
  landing.css
  supplier/reports/report.js
  supplier/supply-edit.html
  supplier/supply-edit.js
  supplier/supply-view.js
Labels: enhancement

#497 admin search filter
  admin/employee/view-all.html
  admin/employee/view-all.js
  admin/user-flow.css
Labels: enhancement

#498 responsive supply view
  common/style.css
  supplier/supply.css
Labels: enhancement

#499 Added supplier qr and fix some bugs for presentation
  admin/employee/view-all.html
  admin/employee/view-all.js
  admin/employee/view.html
  admin/employee/view.js
  collector/collection/complete.js
  collector/collection/enter-amount.js
  common/img/supplier_qr.png
  index.html
  process.html
  products.html
Labels: documentation

#501 Landing footer link bug fixed
  process.html
  products.html
Labels: fixed

#500 fixed device width in css
  admin/collection/collection.css
  admin/user-flow.css
  collector/collection.css
  common/nav.css
  common/notify.css
  common/style.css
  production-manager/user-flow.css
  signin.css
  stock-manager/style.css
  stock-manager/user-flow.css
  supplier/supply-edit.html
  supplier/supply.css
Labels: enhancement

#504 Changed supplier qr
  common/img/supplier_qr.png
Labels: enhancement

#507 added time range text for supply requests
  supplier/supply/pickup-bank.js
  supplier/supply/pickup-cash.js
  supplier/supply/yard-bank.js
  supplier/supply/yard-cash.js
Labels: enhancement

#508 pagination for aome tables
  stock-manager/collectors/view-all.html
  stock-manager/collectors/view-all.js
  stock-manager/production-requests/view-all.html
  stock-manager/production-requests/view-all.js
  stock-manager/supply-requests/index.html
  stock-manager/supply-requests/script.js
Labels: fixed
